// This file has been automatically generated by the i18n-extended cli 
// Do not modify or remove anything from this file 
 
declare const require: any; 

const i18nsrcenwalletxlf = require('raw-loader!src/en/wallet.xlf');

export module i18nExtendedModule {  
 export const translationInterface = [i18nsrcenwalletxlf]; 
 };