// This file has been automatically generated by the i18n-extended cli 
// Do not modify or remove anything from this file 
 
declare const require: any;

export module i18nExtendedModule {  
  export const translationInterface = [];
};