// This file has been automatically generated by the i18n-extended cli 
// Do not modify or remove anything from this file 
 
declare const require: any; 

const i18nlocaleenwalletxlf = require('raw-loader!../locale/en/wallet.xlf');
const i18nlocalefrwalletxlf = require('raw-loader!../locale/fr/wallet.xlf');
const i18nlocaleidwalletxlf = require('raw-loader!../locale/id/wallet.xlf');
const i18nlocaleitwalletxlf = require('raw-loader!../locale/it/wallet.xlf');
const i18nlocalenlwalletxlf = require('raw-loader!../locale/nl/wallet.xlf');
const i18nlocaleplwalletxlf = require('raw-loader!../locale/pl/wallet.xlf');

export const translationInterface = [i18nlocaleenwalletxlf, i18nlocalefrwalletxlf, i18nlocaleidwalletxlf, i18nlocaleitwalletxlf, i18nlocalenlwalletxlf, i18nlocaleplwalletxlf];